// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qztrpzbtoivuqrnhfnaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6dHJwemJ0b2l2dXFybmhmbmF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDA4NjQsImV4cCI6MjA2NTM3Njg2NH0.St12BwEhOPFW3ZgaQ6hG56XTNM_FS9PsW_DeMscVKig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);